In [1]:
import os
import sys
import torch
import numpy as np

In [2]:
#Checking tensor
'''
1.1 torch.is_tensor - returns true if object is a tensor
'''
x=np.matrix('1 2; 3 4')
value=torch.is_tensor(x)
print(f"Is x is tensor: ", value)

Is x is tensor:  False


In [5]:
# Torch tensor
'''
1.2. torch.tensor - Constructs a tensor with data
        - data (array_like) – Can be a list, tuple, NumPy ndarray, scalar, and other types.
'''
# Numpy to Tensor
x=np.matrix('1 2; 3,4')
x_tensor=torch.tensor(x)
print(f"Numpy to Tensor: ", type(x), type(x_tensor), x_tensor, "\n")

Numpy to Tensor:  <class 'numpy.matrix'> <class 'torch.Tensor'> tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 



In [6]:
# list to Tensor
x=[1,2,3,4]
x_tensor=torch.tensor(x)
print(f"List to Tensor: ", type(x), type(x_tensor), x_tensor, "\n")

List to Tensor:  <class 'list'> <class 'torch.Tensor'> tensor([1, 2, 3, 4]) 



In [7]:
# scaler to Tensor
x=3.142
x_tensor=torch.tensor(x)
print(f"Scaler to tensor: ", type(x), type(x_tensor), x_tensor, "\n")

Scaler to tensor:  <class 'float'> <class 'torch.Tensor'> tensor(3.1420) 



In [8]:
#empty list to tensor
x=[]
x_tensor=torch.tensor(x)
print(f"Empty List to Tensor", type(x), type(x_tensor), x_tensor, "\n")

Empty List to Tensor <class 'list'> <class 'torch.Tensor'> tensor([]) 



In [9]:
# From numpy array to Tensor 
# From Tensor to numpy array
'''
1.3 torch.from_numpy() - Numpy to Tensor

    numpy() - Tensor to Numpy

'''
x=np.array([1,2,3])
print(f"Type of x: ", type(x), x,"\n")
x_t=torch.from_numpy(x)
print(f"Type of x_t: ",type(x_t), x_t,"\n")
x_n=x_t.numpy()
print(f"Type of x_n: ", type(x_n), x_n, "\n")


Type of x:  <class 'numpy.ndarray'> [1 2 3] 

Type of x_t:  <class 'torch.Tensor'> tensor([1, 2, 3], dtype=torch.int32) 

Type of x_n:  <class 'numpy.ndarray'> [1 2 3] 



In [10]:
# Zeros
'''
2.1. torch.zeros - Returns a tensor filled with the scalar value 0, with the shape defined by the variable argument
        - sizes - Mention the ND array size
        - dtype - Data type.
'''
x_t1=torch.zeros(2,3)
print("x_t1: ",x_t1)

x_t1:  tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
x_t2=torch.zeros(5)
print(x_t2)

tensor([0., 0., 0., 0., 0.])


In [12]:
x_t2=torch.zeros(4,2,3)
print(x_t2)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [13]:
x_t2.shape

torch.Size([4, 2, 3])

In [14]:
# Ones
'''
2.2. torch.ones - Returns a tensor filled with the scalar value 1, with the shape defined by the variable argument 
        - sizes - Mention the ND array size
        - dtype - Data type.
'''
x_t1=torch.ones(2,3)
print(x_t1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [15]:
x_t2=torch.ones(3,2,4)
print(x_t2)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [17]:
# Empty
'''
2.3. torch.empty - Returns a empty tensor
        - sizes - Mention the ND array size
        - dtype - Data type.
'''
x_t1=torch.empty(2,3)
x_t2=torch.empty(4,2,3)
print(x_t1)
print(x_t2)

tensor([[0.0000e+00, 2.3694e-38, 2.6608e+23],
        [5.4646e-05, 1.0257e-08, 2.6076e-09]])
tensor([[[3.2604e-12, 7.3113e+34, 2.0706e-19],
         [7.7180e+28, 6.0041e+31, 4.2964e+24]],

        [[4.8418e+30, 1.6926e+22, 5.7886e+22],
         [6.7120e+22, 1.1632e+33, 5.6003e-02]],

        [[7.0374e+22, 6.9983e+28, 1.9859e+29],
         [4.3218e+27, 4.7423e+30, 2.2856e+20]],

        [[3.2607e-12, 7.4086e+28, 7.1463e+22],
         [4.6241e+30, 1.0552e+24, 5.5757e-02]]])
